[colors]

# Normal
foreground       = '#cad3f5'
background       = '#24273a'
black            = '#494d64'
blue             = '#8aadf4'
cursor           = '#f4dbd6'
cyan             = '#8bd5ca'
green            = '#a6da95'
magenta          = '#f5bde6'
red              = '#ed8796'
white            = '#b8c0e0'
yellow           = '#eed49f'

# UI colors
tabs             = '#24273a'
tabs-foreground  = '#cad3f5'
tabs-active      = '#b7bdf8'
tabs-active-highlight  = '#b7bdf8'
tabs-active-foreground = '#181926'
selection-foreground   = '#24273a'
selection-background   = '#f4dbd6'

# Dim colors
dim-black        = '#494d64'
dim-blue         = '#8aadf4'
dim-cyan         = '#8bd5ca'
dim-foreground   = '#cad3f5'
dim-green        = '#a6da95'
dim-magenta      = '#f5bde6'
dim-red          = '#ed8796'
dim-white        = '#b8c0e0'
dim-yellow       = '#eed49f'

# Light colors
light-black      = '#5b6078'
light-blue       = '#8aadf4'
light-cyan       = '#8bd5ca'
light-foreground = '#cad3f5'
light-green      = '#a6da95'
light-magenta    = '#f5bde6'
light-red        = '#ed8796'
light-white      = '#a5adcb'
light-yellow     = '#eed49f'
